// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(YiDbContext))]
    [Migration("20230906180827_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("DataLayer.Hexagram", b =>
                {
                    b.Property<int>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Value");

                    b.ToTable("Hexagrams");
                });

            modelBuilder.Entity("DataLayer.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DataLayer.LineText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MainTextId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MainTextId");

                    b.ToTable("LineTexts");
                });

            modelBuilder.Entity("DataLayer.MainText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HexagramValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HexagramValue");

                    b.HasIndex("LanguageId");

                    b.ToTable("Texts");
                });

            modelBuilder.Entity("DataLayer.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseHexagramValue")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChangedHexagramValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseHexagramValue");

                    b.HasIndex("ChangedHexagramValue");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("DataLayer.LineText", b =>
                {
                    b.HasOne("DataLayer.MainText", "MainText")
                        .WithMany("Lines")
                        .HasForeignKey("MainTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainText");
                });

            modelBuilder.Entity("DataLayer.MainText", b =>
                {
                    b.HasOne("DataLayer.Hexagram", null)
                        .WithMany("Texts")
                        .HasForeignKey("HexagramValue");

                    b.HasOne("DataLayer.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DataLayer.Question", b =>
                {
                    b.HasOne("DataLayer.Hexagram", "BaseHexagram")
                        .WithMany()
                        .HasForeignKey("BaseHexagramValue");

                    b.HasOne("DataLayer.Hexagram", "ChangedHexagram")
                        .WithMany()
                        .HasForeignKey("ChangedHexagramValue");

                    b.Navigation("BaseHexagram");

                    b.Navigation("ChangedHexagram");
                });

            modelBuilder.Entity("DataLayer.Hexagram", b =>
                {
                    b.Navigation("Texts");
                });

            modelBuilder.Entity("DataLayer.MainText", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
