// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(YiDbContext))]
    partial class YiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("DataLayer.Hexagram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Hexagrams");
                });

            modelBuilder.Entity("DataLayer.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DataLayer.LineText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TextId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TextId");

                    b.ToTable("LineTexts");
                });

            modelBuilder.Entity("DataLayer.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseHexagramId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangedHexagramId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseHexagramId");

                    b.HasIndex("ChangedHexagramId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("DataLayer.Text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HexagramId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HexagramId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Texts");
                });

            modelBuilder.Entity("DataLayer.LineText", b =>
                {
                    b.HasOne("DataLayer.Text", null)
                        .WithMany("Lines")
                        .HasForeignKey("TextId");
                });

            modelBuilder.Entity("DataLayer.Question", b =>
                {
                    b.HasOne("DataLayer.Hexagram", "BaseHexagram")
                        .WithMany()
                        .HasForeignKey("BaseHexagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Hexagram", "ChangedHexagram")
                        .WithMany()
                        .HasForeignKey("ChangedHexagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseHexagram");

                    b.Navigation("ChangedHexagram");
                });

            modelBuilder.Entity("DataLayer.Text", b =>
                {
                    b.HasOne("DataLayer.Hexagram", null)
                        .WithMany("Texts")
                        .HasForeignKey("HexagramId");

                    b.HasOne("DataLayer.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DataLayer.Hexagram", b =>
                {
                    b.Navigation("Texts");
                });

            modelBuilder.Entity("DataLayer.Text", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
